In [2]:
#Importamos numpy
import numpy as np

In [3]:
a1=np.array([1,2,3]) #Con una lista
type(a1) #Verificamos el array

numpy.ndarray

In [5]:
a2=np.arange(10) #Creamos un array de 0 a 9 


In [6]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a3=np.zeros((2,3)) #Creamos una lista de dos dimensiones, como tupla que lo llene con ceros
a4=np.ones((2,3))

In [11]:
from IPython.display import display # Es para mostrar el tipo tambien del array
display(a3)
display(a4)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# np.linspace(a,b,c) son numeros con decimales entre un rango en especifico, distanciados de forma regular. La distancia sera entre 
#(a-b) /(n-1)

In [12]:
a5=np.linspace(0,1,10)
display(a5)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
#Los array estan fuertemente tipificados 
a5.dtype #Nos muestra que son flotantes de 64 bits 

dtype('float64')

In [14]:
a1.shape #No aparece en la 2 porque no es un array de dos dimensiones 

(3,)

In [15]:
a3.shape #Una tupla de 2,3 

(2, 3)

In [17]:
a1D=np.array([1,2,3])#No es considerado una matrix
a2D=np.array([[1,2,3]])#1 linea con 3 columnas
display(a1D.shape)
display(a2D.shape)


(3,)

(1, 3)

In [18]:
#Comparamos dos arrays
np.array_equal(a1D,a2D) #Apesar de tener los mismos elementos no quiere decir que sean iguales .

False

In [22]:
#Reshaping , cambiar la estructura de un array
new_dims=(1,a1D.shape[0]) 
a=a1D.reshape(new_dims) 

In [23]:
a.shape #No aparece en la 2 porque no es un array de dos dimensiones 

(1, 3)

In [24]:
#Ahora lo comparamos 
np.array_equal(a,a2D)

True

In [25]:
#Creamos una matrix
a=np.array([[1,0,3],[2,5,3],[1,6,9]])
a

array([[1, 0, 3],
       [2, 5, 3],
       [1, 6, 9]])

In [29]:
#Accedemos a un elemento de la matrix
a[0,0] #Primer argumento es la fila y la otra es la columna


1

In [28]:
a[2,2]

9

In [30]:
ar1=np.arange(10)
ar2=np.eye(3)
display(ar1)
display(ar2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
#Slices 
ar1[:5] #Desde la posicion 0 hasta la 5

array([0, 1, 2, 3, 4])

In [34]:
ar2[0:3,1]#Tomamos todas las filas y solo mostramos la columna 1 

array([0., 1., 0.])