In [2]:
#Importamos numpy
import numpy as np

In [3]:
a1=np.array([1,2,3]) #Con una lista
type(a1) #Verificamos el array

numpy.ndarray

In [5]:
a2=np.arange(10) #Creamos un array de 0 a 9 


In [6]:
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a3=np.zeros((2,3)) #Creamos una lista de dos dimensiones, como tupla que lo llene con ceros
a4=np.ones((2,3))

In [11]:
from IPython.display import display # Es para mostrar el tipo tambien del array
display(a3)
display(a4)

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# np.linspace(a,b,c) son numeros con decimales entre un rango en especifico, distanciados de forma regular. La distancia sera entre 
#(a-b) /(n-1)

In [12]:
a5=np.linspace(0,1,10)
display(a5)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
#Los array estan fuertemente tipificados 
a5.dtype #Nos muestra que son flotantes de 64 bits 

dtype('float64')